# Generated by Django 4.1.1 on 2022-10-06 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='creat_time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update_time')),
                ('delete_time', models.DateTimeField(blank=True, null=True, verbose_name='delete_time')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is_deleted')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=100)),
                ('q_level', models.CharField(choices=[('0', 'easy'), ('1', 'normal'), ('2', 'hard')], default=None, max_length=1, null=True)),
            ],
            options={
                'ordering': ['-create_time'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='creat_time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update_time')),
                ('delete_time', models.DateTimeField(blank=True, null=True, verbose_name='delete_time')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is_deleted')),
                ('false_answer', models.IntegerField()),
                ('true_answer', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
            options={
                'verbose_name': 'exams',
                'verbose_name_plural': 'exam',
            },
        ),
    ]
