# Generated by Django 4.1.1 on 2022-10-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='number',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='exam',
            name='false_answer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exam',
            name='true_answer',
            field=models.IntegerField(default=0),
        ),
    ]
