# Generated by Django 4.1.1 on 2022-10-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_exam_number_alter_exam_false_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='question_passed',
            field=models.IntegerField(default=0),
        ),
    ]
