# Generated by Django 4.1.1 on 2022-10-07 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='User',
            new_name='user',
        ),
    ]
